# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(default='test1', max_length=50, verbose_name='username')),
                ('email', models.EmailField(default='test1@wanda.cn', max_length=254, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_stuff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
