# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20170718_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='desc',
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='issue title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='jira_link',
            field=models.CharField(max_length=200),
        ),
    ]
