# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 09:52
from __future__ import unicode_literals

from django.db import migrations, models


def update_issue_description(apps, update_data):
    status_arr = {'未处理': "suspending", '已处理': "handling", '已关闭': "closed"}
    TaskStatus = apps.get_model('issue', 'issuestatus')
    for k, v in status_arr.items():
        TaskStatus.objects.filter(name=k).update(description=v)

class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20170829_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuestatus',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='状态描述'),
        ),
        migrations.RunPython(update_issue_description),
    ]
