# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_issuestatus_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-updated_time', '-created_time', 'type')},
        ),
    ]
