# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20170922_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='业务模块名称')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='业务模块描述')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='手机品牌')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='所属大区')),
            ],
        ),
    ]
