# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def preset_priority(apps, schema_editor):
    model = apps.get_model('issue', 'IssuePriority')
    for name, desc in (('urgent', '紧急'), ('normal', '一般'), ('unurgent', '不紧急')):
        model.objects.get_or_create(name=name, desc=desc)


def set_issue_priority(apps, schema_editor):
    model = apps.get_model('issue', 'Issue')
    model.objects.all().update(priority=apps.get_model('issue', 'IssuePriority').objects.get(name='normal'))


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_auto_20170925_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='英文名称')),
                ('desc', models.CharField(max_length=100, unique=True, verbose_name='中文描述')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.IssuePriority'),
        ),
        migrations.RunPython(preset_priority, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_issue_priority, reverse_code=migrations.RunPython.noop),
    ]
