# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 10:54
from __future__ import unicode_literals

from django.db import migrations


def modify_issues(apps, update_data):
    TaskStatus = apps.get_model('issue', 'issuestatus')
    TaskStatus.objects.filter(name='已关闭').update(name='关闭')
    TaskStatus.objects.filter(name='未处理').update(name='待处理')
    TaskStatus.objects.filter(name='已处理').update(name='处理中')
    obj, _ = TaskStatus.objects.get_or_create(name='新增')
    obj.description = 'new'
    obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0010_auto_20170929_1211'),
    ]

    operations = [
        migrations.RunPython(modify_issues, reverse_code=migrations.RunPython.noop)
    ]
