# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0012_auto_20171013_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-created_time', 'type')},
        ),
    ]
