# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_auto_20171017_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmodule',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='phonebrand',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('id',)},
        ),
    ]
