# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


def change_issue_status(apps, schema_editor):
    status = apps.get_model('issue', 'IssueStatus')
    status.objects.filter(name='待处理').update(description='todo')


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0014_auto_20171018_1707'),
    ]

    operations = [
        migrations.RunPython(change_issue_status),
        migrations.AlterField(
            model_name='issuestatus',
            name='description',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='状态描述'),
        ),
    ]
