# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0018_auto_20171031_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='zc_change_logs',
            field=models.TextField(blank=True, null=True, verbose_name='众测平台操作日志'),
        ),
    ]
