# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0018_auto_20171117_1650'),
        ('issue', '0019_issue_zc_change_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueExtValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(verbose_name='扩展字段值')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.IssueExtField')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_values', to='issue.Issue', verbose_name='对应的issue')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issueextvalue',
            unique_together=set([('issue', 'field')]),
        ),
    ]
