# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0021_auto_20171122_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmoduletree',
            options={'ordering': ('level', 'disabled', '-id')},
        ),
        migrations.AddField(
            model_name='businessmoduletree',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='业务模块是否下架'),
        ),
    ]
