# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0022_auto_20171123_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmoduletree',
            name='name',
            field=models.CharField(max_length=50, verbose_name='业务模块名称'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmoduletree',
            unique_together=set([('name', 'parent')]),
        ),
    ]
