# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0023_auto_20171127_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_issues', to=settings.AUTH_USER_MODEL, verbose_name='经办人'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
