# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('strategy', '0002_auto_20170628_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_group', '0003_usergroup_users'),
        ('task_manager', '0002_auto_20170627_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotInnerStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='内灰策略名称')),
                ('push_content', models.TextField(default='', verbose_name='推送内容')),
                ('index', models.IntegerField(default=0, verbose_name='策略顺序')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gray_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.GrayTask', verbose_name='灰度任务id')),
                ('push_channels', models.ManyToManyField(blank=True, to='strategy.PushChannel')),
                ('user_groups', models.ManyToManyField(blank=True, to='user_group.UserGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnapshotOuterStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='外灰策略名称')),
                ('version', models.CharField(default='', max_length=255, verbose_name='版本')),
                ('allow_users', models.TextField(verbose_name="外灰用户列表", default="")),
                ('range_dates', models.CharField(default='', max_length=2048, verbose_name='外灰时间范围及次数限额')),
                ('cities', models.CharField(default='', max_length=1024, verbose_name='城市列表')),
                ('city_enable', models.BooleanField(default=True, verbose_name='包含或不包含城市')),
                ('percentage', models.IntegerField(default=0, verbose_name='百分比')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('is_compatible', models.IntegerField(default=0, verbose_name='是否强制执行')),
                ('frequency', models.IntegerField(default=0, verbose_name='每天提示次数')),
                ('change_log', models.TextField(verbose_name="推送给app的内容", default="")),
                ('change_log_img', models.CharField(default='', max_length=200, verbose_name='上传到图床返回的名称')),
                ('index', models.IntegerField(verbose_name='策略顺序')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
                ('channels', models.ManyToManyField(blank=True, to='strategy.Channel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gray_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.GrayTask', verbose_name='灰度任务id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='innerstrategy',
            name='gray_task',
        ),
        migrations.RemoveField(
            model_name='outerstrategy',
            name='gray_task',
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='inner_Strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.SnapshotInnerStrategy', verbose_name='内部策略'),
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='outer_Strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.SnapshotOuterStrategy', verbose_name='外部策略'),
        ),
        migrations.DeleteModel(
            name='InnerStrategy',
        ),
        migrations.DeleteModel(
            name='OuterStrategy',
        ),
    ]
