# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20170705_1624'),
        ('task_manager', '0004_auto_20170706_1706'),
    ]

    operations = [
    ]
