# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_merge_20170707_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='grayappversion',
            name='android_version',
            field=models.CharField(default='', max_length=256, verbose_name='android版本名称'),
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='ios_version',
            field=models.CharField(default='', max_length=256, verbose_name='android版本号'),
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='release_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graytaskrunstatus',
            name='current_step_name',
            field=models.CharField(default='', max_length=256, verbose_name='当前步骤'),
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='current_step',
            field=models.IntegerField(default=0, verbose_name='当前步骤'),
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='is_current_use',
            field=models.BooleanField(default=False, verbose_name='是否当前使用'),
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='inner_Strategy',
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='outer_Strategy',
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='update_info',
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='version_name',
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='version_number',
        ),
        migrations.AlterUniqueTogether(
            name='grayappversion',
            unique_together=set([('gray_task', 'current_step')]),
        ),
    ]
