# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 12:53
from __future__ import unicode_literals

from django.db import migrations


def preset_gray_status(apps, schema_editor):
    status_arr = ['preparation', 'testing', 'finished']
    type_model = apps.get_model('task_manager', 'graystatus')
    for status in status_arr:
        type_model.objects.get_or_create(name=status)


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_auto_20170710_1526'),
    ]

    operations = [migrations.RunPython(preset_gray_status)]
