# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_auto_20170719_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graytask',
            name='current_step',
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='android_download_url',
            field=models.CharField(default='', max_length=1000, verbose_name='版本下载链接'),
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='android_release_date',
            field=models.DateField(null=True, verbose_name='版本创建时间'),
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='current_step_name',
            field=models.CharField(default='', max_length=256, verbose_name='当前策略名称'),
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='ios_download_url',
            field=models.CharField(default='', max_length=1000, verbose_name='版本下载链接'),
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='ios_release_date',
            field=models.DateField(null=True, verbose_name='版本创建时间'),
        ),
        migrations.AddField(
            model_name='graytask',
            name='android_download',
            field=models.IntegerField(default=0, verbose_name='android所有版本下载量和'),
        ),
        migrations.AddField(
            model_name='graytask',
            name='inner_strategy_steps',
            field=models.IntegerField(default=0, verbose_name='内部策略总步数'),
        ),
        migrations.AddField(
            model_name='graytask',
            name='ios_download',
            field=models.IntegerField(default=0, verbose_name='ios所有版本下载量和'),
        ),
        migrations.AddField(
            model_name='graytask',
            name='total_strategy_steps',
            field=models.IntegerField(default=0, verbose_name='策略总步数'),
        ),
        migrations.AlterUniqueTogether(
            name='grayappversion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='app',
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='grayappversion',
            name='release_date',
        ),
    ]
