# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0010_auto_20170726_1928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grayappversion',
            unique_together=set([]),
        ),
    ]
