# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_auto_20170727_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graytask',
            name='android_download',
        ),
        migrations.RemoveField(
            model_name='graytask',
            name='ios_download',
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='android_download_number',
            field=models.IntegerField(default=0, verbose_name='android版本下载量'),
        ),
        migrations.AddField(
            model_name='grayappversion',
            name='ios_download_number',
            field=models.IntegerField(default=0, verbose_name='ios版本下载量'),
        ),
    ]
