# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_auto_20170728_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='graytask',
            name='award_rules',
            field=models.TextField(blank=True, null=True, verbose_name='获奖规则, 支持文本'),
        ),
        migrations.AddField(
            model_name='graytask',
            name='contact_way',
            field=models.TextField(blank=True, null=True, verbose_name='联系方式, 支持文本'),
        ),
        migrations.AddField(
            model_name='graytask',
            name='version_desc',
            field=models.TextField(blank=True, null=True, verbose_name='版本描述信息, 支持文本'),
        ),
    ]
