# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0014_auto_20170829_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graytask',
            name='task_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='任务名称'),
        ),
    ]
