# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0015_auto_20170831_0925'),
        ('task_manager', '0015_auto_20170830_1719'),
    ]

    operations = [
    ]
