# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0016_merge_20170901_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grayappversion',
            name='android_download_url',
            field=models.CharField(default='', max_length=1000, verbose_name='android版本下载链接'),
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='android_release_date',
            field=models.DateField(null=True, verbose_name='android版本创建时间'),
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='ios_download_url',
            field=models.CharField(default='', max_length=1000, verbose_name='ios版本下载链接'),
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='ios_release_date',
            field=models.DateField(null=True, verbose_name='ios版本创建时间'),
        ),
        migrations.AlterField(
            model_name='grayappversion',
            name='ios_version',
            field=models.CharField(default='', max_length=256, verbose_name='ios版本号'),
        ),
    ]
