# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0017_auto_20170911_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueExtField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('default', models.CharField(blank=True, max_length=200, null=True, verbose_name='字段默认值')),
                ('is_optional', models.BooleanField(default=True, verbose_name='是否为可选，默认为可选')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='字符串表示字段类型，未指定则字段为字符串类型')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_fields', to='task_manager.GrayTask', verbose_name='对其问题做字段扩展的任务')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issueextfield',
            unique_together=set([('task', 'name')]),
        ),
    ]
