# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0018_auto_20171117_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='graytask',
            name='is_join_kesutong',
            field=models.BooleanField(default=False, verbose_name='是否接入客诉通找茬'),
        ),
    ]
