# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_appmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodule',
            name='app',
        ),
        migrations.DeleteModel(
            name='AppModule',
        ),
    ]
