# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170628_0205'),
        ('common', '0003_auto_20170629_1023'),
    ]

    operations = [
    ]
