# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170629_1517'),
        ('common', '0004_merge_20170629_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_time',
        ),
    ]
