# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodule',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.App'),
        ),
        migrations.AlterField(
            model_name='appmodule',
            name='module_name',
            field=models.CharField(max_length=30),
        ),
    ]
