# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20170726_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodule',
            name='module_name',
            field=models.CharField(max_length=100),
        ),
    ]
