# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170731_1512'),
        ('common', '0010_auto_20170726_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appmodule',
            unique_together=set([('app', 'module_name')]),
        ),
    ]
