# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='link_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
