# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 15:41
from __future__ import unicode_literals

import benchmark_django_rest_framework.benchmark_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersions',
            fields=[
                ('version', models.IntegerField(primary_key=True, serialize=False)),
                ('app_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('allow_users', models.CharField(max_length=512)),
                ('range_dates', models.CharField(max_length=256)),
                ('citys', models.CharField(max_length=256)),
                ('city_enable', models.IntegerField()),
                ('percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_versions',
                'managed': False,
            },
            bases=(benchmark_django_rest_framework.benchmark_model.BenchmarkModel, models.Model),
        ),
        migrations.CreateModel(
            name='Clientversion',
            fields=[
                ('cvid', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('clienttype', models.SmallIntegerField()),
                ('version_name', models.CharField(max_length=20)),
                ('changelogimg', models.CharField(blank=True, max_length=200, null=True)),
                ('changelog', models.CharField(blank=True, max_length=20000, null=True)),
                ('size', models.IntegerField()),
                ('url', models.CharField(max_length=256)),
                ('iscompatible', models.SmallIntegerField()),
                ('createtime', models.DateTimeField()),
                ('minimumversion', models.IntegerField()),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'clientversion',
                'managed': False,
            },
            bases=(benchmark_django_rest_framework.benchmark_model.BenchmarkModel, models.Model),
        ),
    ]
