# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def preset_user_roles(apps, schema_editor):
    types = ['admin', 'app_owner']
    role_model = apps.get_model('gated_launch_auth', 'Role')
    for t in types:
        role_model.objects.create(name=t)


class Migration(migrations.Migration):

    dependencies = [
        ('gated_launch_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gated_launch_auth.Role'),
        ),
        migrations.RunPython(preset_user_roles, reverse_code=migrations.RunPython.noop),
    ]
