# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gated_launch_auth', '0002_auto_20170628_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
