# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gated_launch_auth', '0003_auto_20170629_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
