# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gated_launch_auth', '0006_auto_20170726_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weixin_openid',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
    ]
