# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 10:27
from __future__ import unicode_literals

from django.db import migrations, models


def preset_app_type(apps, schema_editor):
    types = ['ios', 'android']
    type_model = apps.get_model('app', 'AppType')
    for t in types:
        type_model.objects.get_or_create(name=t)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0002_auto_20170629_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='app',
            name='type',
        ),
        migrations.AddField(
            model_name='app',
            name='types',
            field=models.ManyToManyField(to='app.AppType'),
        ),
        migrations.RunPython(preset_app_type, reverse_code=migrations.RunPython.noop),
    ]
