# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0002_auto_20170629_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='managers',
        ),
    ]
