# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_app_managers'),
        ('app', '0002_auto_20170630_1027'),
    ]

    operations = [
    ]
