# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_app_apphub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='bp_app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
