# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_app_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='bp_channels_name',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
