# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_app_bp_channels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='bp_channels_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
