# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from gated_launch_backend import settings


def preset_components(apps, schema_editor):
    components_arr = [
        {
            "name": "技术支持",
            "desc": "微信小程序对应的jira模块",
            "operator": "ffan_support"
        },
        {
            "name": "飞凡众测",
            "desc": "飞凡app对应的jira模块",
            "operator": "wangdaifu"
        },
        {
            "name": "万益通众测",
            "desc": "万益通app对应的jira模块",
            "operator": "luowei32"
        }
    ]
    type_model = apps.get_model('app', 'AppComponent')
    user_model = apps.get_model('gated_launch_auth', 'User')
    for component in components_arr:
        type_model.objects.get_or_create(name=component["name"],
                                         desc=component["desc"],
                                         operator=user_model.objects.get_or_create(username=component["operator"])[0])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170927_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='模块名称')),
                ('desc', models.CharField(max_length=100, verbose_name='模块描述')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL,
                                               verbose_name="默认经办人"))
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(preset_components, reverse_code=migrations.RunPython.noop),
    ]
