# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def update_app_component(apps, update_data):
    components_arr = {"飞凡众测": "飞凡",
                      "万益通众测": "万益通",
                      "技术支持": "微信小程序飞凡"}
    AppComponent = apps.get_model('app', 'AppComponent')
    App = apps.get_model('app', 'App')
    for k, v in components_arr.items():
        App.objects.filter(name=v).update(component=AppComponent.objects.get(name=k))


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_appcomponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.AppComponent'),
        ),
        migrations.RunPython(update_app_component, reverse_code=migrations.RunPython.noop),
    ]
