# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171201_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='状态名称')),
                ('description', models.CharField(default='', max_length=256, verbose_name='状态中文名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='app',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AppStatus'),
        ),
    ]
