# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 12:53
from __future__ import unicode_literals

from django.db import migrations


def preset_app_status(apps, schema_editor):
    status_arr = ['unReviewed', 'reviewedPass', 'reviewedFail']
    type_model = apps.get_model('app', 'AppStatus')
    for status in status_arr:
        type_model.objects.get_or_create(name=status)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171206_0926'),
    ]

    operations = [migrations.RunPython(preset_app_status, reverse_code=migrations.RunPython.noop)]
