# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Image'),
        ),
        migrations.AlterField(
            model_name='app',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='app.AppType'),
        ),
    ]
