# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171208_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='types',
            field=models.ManyToManyField(blank=True, to='app.AppType'),
        ),
    ]
