# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_group', '0002_auto_20170621_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
