# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_user_group_type(apps, schema_editor):
    type_model = apps.get_model('user_group', 'UserGroupType')
    type_model.objects.get_or_create(name='owner')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_group', '0003_usergroup_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='users',
            new_name='members',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.App'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_user_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(add_user_group_type, reverse_code=migrations.RunPython.noop),
    ]
