# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('user_group', '0004_auto_20170628_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergrouptype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set([('app', 'name')]),
        ),
    ]
