# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0005_auto_20170629_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_user_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
