# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0006_auto_20170629_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.App'),
        ),
    ]
