# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0007_auto_20170630_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_user_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
