# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 18:18
from __future__ import unicode_literals

from django.db import migrations
from apps.user_group.models import UserGroupType


def preset_company_group(apps, schema_editor):
    type_model = apps.get_model('user_group', 'UserGroupType')
    group_model = apps.get_model('user_group', 'UserGroup')

    company_type = type_model.objects.get(name=UserGroupType.COMPANY)
    if not group_model.objects.filter(type=company_type).exists():
        group_model.objects.create(name='company_user_group', type=company_type)


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0008_auto_20170726_1537'),
    ]

    operations = [
        migrations.RunPython(preset_company_group, reverse_code=migrations.RunPython.noop),
    ]
