# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


def preset_push_channel(apps, schema_editor):
    channels = ['sms', 'mail']
    type_model = apps.get_model('strategy', 'PushChannel')
    for c in channels:
        type_model.objects.get_or_create(name=c)


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20170705_1624'),
        ('strategy', '0002_auto_20170628_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outerstrategy',
            name='channels',
        ),
        migrations.AddField(
            model_name='outerstrategy',
            name='channels',
            field=models.TextField(default='', verbose_name='外灰渠道'),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.RunPython(preset_push_channel, reverse_code=migrations.RunPython.noop),
    ]
