# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20170705_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outerstrategy',
            name='allow_users',
            field=models.TextField(blank=True, default='', verbose_name='外灰用户列表'),
        ),
        migrations.AlterField(
            model_name='outerstrategy',
            name='change_log',
            field=models.TextField(blank=True, default='', verbose_name='推送给app的内容'),
        ),
        migrations.AlterField(
            model_name='outerstrategy',
            name='change_log_img',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='上传到图床返回的名称'),
        ),
        migrations.AlterField(
            model_name='outerstrategy',
            name='channels',
            field=models.TextField(blank=True, default='', verbose_name='外灰渠道'),
        ),
        migrations.AlterField(
            model_name='outerstrategy',
            name='cities',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='城市列表'),
        ),
        migrations.AlterField(
            model_name='outerstrategy',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, verbose_name='百分比'),
        ),
        migrations.AlterField(
            model_name='outerstrategy',
            name='range_dates',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='外灰时间范围及次数限额'),
        ),
        migrations.AlterField(
            model_name='outerstrategy',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='版本'),
        ),
    ]
