# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_app_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0004_auto_20170719_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='', max_length=255, verbose_name='策略类型')),
                ('name', models.CharField(default='', max_length=255, verbose_name='策略名称')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inner_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.InnerStrategy')),
                ('outer_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.OuterStrategy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
