# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170629_1517'),
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='image_url',
        ),
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Image'),
            preserve_default=False,
        ),
    ]
